name: Frontend Build and EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: cd frontend && npm install

      # - name: Run Tests
      #   run: cd frontend && npm test

      - name: Create Production Build
        run: cd frontend && npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Backend Dependencies
        run: cd backend && npm install

      - name: Deploy
        run: cd backend && npm run-script deploy