name: Frontend Build and EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: cd frontend && npm install

      # - name: Run Tests
      #   run: cd frontend && npm test

      - name: Create Production Build
        run: cd frontend && npm run build

      - name: Upload build directory
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: frontend/build/

      - name: List build directory
        run: ls -la frontend/build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Backend Dependencies
        run: cd backend && npm install

      - name: Setup SSH for EC2
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Disable Host Key Checking
        run: |
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Download build directory
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: frontend/build/

      - name: Transfer build to remote server
        run: |
          rsync -avz -e 'ssh -o StrictHostKeyChecking=no' frontend/build/ ubuntu@${{ secrets.EC2_IP }}:/var/www/portfolio/build/

      - name: Deploy
        run: cd backend && npm run-script deploy

